# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contan', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='cursuri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contan.Curs'),
        ),
    ]
