# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contan', '0003_auto_20161126_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cursuri_inscris',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='college',
            name='cursuri',
            field=models.TextField(),
        ),
    ]
